name: Compilar código C++ con ncurses en Windows
on: [push]
jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Instalar dependencias
        uses: actions/checkout@v3

      - name: Configurar MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            ncurses
            mingw-w64-ucrt-x86_64-gcc
          check-installed: true

      - name: Compilar el proyecto
        run: |
          make -f ./makefile
