name: Compilar código C++ con ncurses en Windows
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Instalar ncurses
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-WebRequest https://github.com/msys2/msys2/releases/download/v6.0/msys2-installer.exe -OutFile msys2-installer.exe
          Start-Process msys2-installer.exe -ArgumentList "/VERYSILENT /NORESTART /SP-"
      - name: Clonar el repositorio
        uses: actions/checkout@v2
      - name: Compilar el código
        run: |
          cd ./build
          mkdir -p ./build
          cd ./build
          cmake .. -G "MinGW Makefiles"
          make -f ../makefile
